"""training_events

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-05 15:12:35.599027+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('exercise', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('schema_v', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts', 'exercise', 'kind', 'reps', name='uq_training_events_natural')
    )
    op.create_index('ix_training_events_local_date_exercise', 'training_events', ['local_date', 'exercise'], unique=False)
    op.create_index(op.f('ix_training_events_ts'), 'training_events', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_events_ts'), table_name='training_events')
    op.drop_index('ix_training_events_local_date_exercise', table_name='training_events')
    op.drop_table('training_events')
    # ### end Alembic commands ###
