"""training_events_hold_kind

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-05 15:26:53.206278+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_events', sa.Column('duration_s', sa.Integer(), nullable=True))
    op.drop_constraint('uq_training_events_natural', 'training_events', type_='unique')
    op.create_unique_constraint('uq_training_events_natural', 'training_events', ['ts', 'exercise', 'kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_training_events_natural', 'training_events', type_='unique')
    op.create_unique_constraint('uq_training_events_natural', 'training_events', ['ts', 'exercise', 'kind', 'reps'])
    op.drop_column('training_events', 'duration_s')
    # ### end Alembic commands ###
